remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 猫哥的技术杂货铺
description: My tech blog website hosted at GitHub
